# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc "Fast terminal git client for very large monorepos (TUI + scriptable CLI)"
  homepage "https://github.com/homeend/gigagit"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeend/gigagit/releases/download/v0.2.3/gg_0.2.3_darwin_amd64.tar.gz"
      sha256 "f40f39f6b2f15cc72243554935576e349896acd9b82cfec1ab68c2e4d756c643"

      define_method(:install) do
        bin.install "gg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeend/gigagit/releases/download/v0.2.3/gg_0.2.3_darwin_arm64.tar.gz"
      sha256 "0c5fb1fe4b0412ed04a24f516c01403e693c4dfca8b0d28a71586d05fdd86189"

      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/gigagit/releases/download/v0.2.3/gg_0.2.3_linux_amd64.tar.gz"
      sha256 "a4d44c681f638da815a80ea1d2e33f52ec9926a4b874fb5a7ac47b61b475fa59"
      define_method(:install) do
        bin.install "gg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/gigagit/releases/download/v0.2.3/gg_0.2.3_linux_arm64.tar.gz"
      sha256 "d4c7cb43db9807419fa48f13c6dae2a4bbaba6d411feff5f4e40b60aee90ab3a"
      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gg version")
  end
end
