# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogListener < Formula
  desc "Real-time multi-source log tailer with regex file discovery, TUI, and MCP server"
  homepage "https://github.com/homeend/log-listener"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeend/log-listener/releases/download/v0.1.4/log-listener_0.1.4_darwin_amd64.tar.gz"
      sha256 "368c045116facc76538036b5f0fd83ce6acd5e1cf6c10e485c6992623f16deec"

      define_method(:install) do
        bin.install "log-listener"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeend/log-listener/releases/download/v0.1.4/log-listener_0.1.4_darwin_arm64.tar.gz"
      sha256 "485a01604cca427681e01fe2f89cb4aa631f3cd1aaa809a02971545caaa1af93"

      define_method(:install) do
        bin.install "log-listener"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/log-listener/releases/download/v0.1.4/log-listener_0.1.4_linux_amd64.tar.gz"
      sha256 "0411400862c9b7ec1ecd50cd78a59ae4bf2c369cb7a31f5069d5d46d98c7c002"
      define_method(:install) do
        bin.install "log-listener"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/log-listener/releases/download/v0.1.4/log-listener_0.1.4_linux_arm64.tar.gz"
      sha256 "6a6e3269949c4f222482a811827908127bb16a64d39e75563c49803a124037d9"
      define_method(:install) do
        bin.install "log-listener"
      end
    end
  end

  test do
    assert_match "unknown flag", shell_output("#{bin}/log-listener --help 2>&1", 2)
  end
end
