# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Fast git worktree manager with lifecycle hooks and cd-on-switch shell integration"
  homepage "https://github.com/homeend/worktrees"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.0/wt_0.2.0_darwin_amd64.tar.gz"
      sha256 "993322663dd93bb39345b9fb180f5ce7e579316ff9bc25f47010212ddfadac66"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.0/wt_0.2.0_darwin_arm64.tar.gz"
      sha256 "07bc38cfb1a37bbb79f6573c92c45aec8ddf9a36639106ce97b507f7c4e24a35"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.0/wt_0.2.0_linux_amd64.tar.gz"
      sha256 "37809bd38ee08282d9b7c124b0154fbc1583fe275ddb9001bc90798f6493fc24"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.0/wt_0.2.0_linux_arm64.tar.gz"
      sha256 "dba80a5c922cdf06b345553ee94c9e9e11f939cd880f8bb3069b1cc0a6451b81"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      For cd-on-Enter in the TUI, install the shell function once:
        eval "$(wt shell-init zsh)"    # or: shell-init bash
    EOS
  end

  test do
    system "#{bin}/wt", "--help"
  end
end
