# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Fast git worktree manager with lifecycle hooks and cd-on-switch shell integration"
  homepage "https://github.com/homeend/worktrees"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.3/wt_0.2.3_darwin_amd64.tar.gz"
      sha256 "bde289e1262778ada88bb334330a5c8f66cb745c0e4740b35a2782e670258142"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.3/wt_0.2.3_darwin_arm64.tar.gz"
      sha256 "af4994adda54e1c2d4fc2ba57e857971cb67eb53e3956cbe9bc6ca174040ddb0"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.3/wt_0.2.3_linux_amd64.tar.gz"
      sha256 "e3ebaba3674dbd5b2f03cf186b40251759894a6eb8124388c9ea4b5d6cee819c"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.3/wt_0.2.3_linux_arm64.tar.gz"
      sha256 "dc13a9cc257f3c3ccdac84106f45ad9bf8824eb810940e8e06639cfb70074811"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      For cd-on-Enter in the TUI, add to ~/.zshrc / ~/.bashrc:
        eval "$(wt shell-init zsh)"    # or: shell-init bash
      Use exactly that eval-from-PATH form. Do NOT use
      `wt shell-init --install` with a brew-installed wt: it pins the
      version-numbered Cellar path, which breaks on the next upgrade.
    EOS
  end

  test do
    system "#{bin}/wt", "--help"
  end
end
