# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Fast git worktree manager with lifecycle hooks and cd-on-switch shell integration"
  homepage "https://github.com/homeend/worktrees"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.2/wt_0.2.2_darwin_amd64.tar.gz"
      sha256 "69e00667157cd83cb3c2c15b12752c4e85c0b19a9ca0e306fbc24622fb65cd3d"

      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.2/wt_0.2.2_darwin_arm64.tar.gz"
      sha256 "636e33b709af413cddb1a23cda301068f898ecc85bb1c06fd3cc70636efb3d6f"

      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.2/wt_0.2.2_linux_amd64.tar.gz"
      sha256 "ae47cde5c5680e407af622ae8309b6db8afc4fb9c79c7420370196d93e5fb771"
      define_method(:install) do
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeend/worktrees/releases/download/v0.2.2/wt_0.2.2_linux_arm64.tar.gz"
      sha256 "6bfa62e025e7f31909ee00ce67d4f96d48d5b2847c7e3f09ac107cc0d4e3a856"
      define_method(:install) do
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      For cd-on-Enter in the TUI, add to ~/.zshrc / ~/.bashrc:
        eval "$(wt shell-init zsh)"    # or: shell-init bash
      Use exactly that eval-from-PATH form. Do NOT use
      `wt shell-init --install` with a brew-installed wt: it pins the
      version-numbered Cellar path, which breaks on the next upgrade.
    EOS
  end

  test do
    system "#{bin}/wt", "--help"
  end
end
